export enum Industry {
  FINTECH = 'FINTECH',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  ECOMMERCE = 'ECOMMERCE',
  AI = 'AI',
  BLOCKCHAIN = 'BLOCKCHAIN',
  GREEN_TECH = 'GREEN_TECH',
  LOGISTICS = 'LOGISTICS',
  AGRITECH = 'AGRITECH',
  OTHER = 'OTHER',
  TECHNOLOGY = "TECHNOLOGY"
}